# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://id4ac.github.io/'
baseurl: ''
title: 'IDC Workshop'
description: 'Interactive Design with Autistic Children using LLM and IoT for Personalized Training'
permalink: pretty
logo: "https://idc.acm.org/2024/wp-content/uploads/2023/10/cropped-cropped-logo-IDC24-orginieel-300x153.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
