# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://id4ac.github.io/'
baseurl: ''
title: 'UbiComp 2024 Workshop'
description: 'Interactive Design with Autistic Children using LLM and IoT for Personalized Training: The Good, The Bad and The Challenging'
permalink: pretty
logo: "https://www.ubicomp.org/ubicomp-iswc-2024/wp-content/uploads/2023/09/web.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Footer nav
navigation_footer:
- title: Back to top | Designed bu Zian Jin
  url: "#top"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
